-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

--seq
sequelize model:generate --name usertest --attributes userid:integer[] , username:string , password:string , email:string, created_at:date 
CREATE TABLE public."User"
(
    username string NOT NULL,
    password string NOT NULL,
    email string NOT NULL,
    dt_last_visit date,
    dt_registered date NOT NULL,
    last_online time with time zone,
    userid integer NOT NULL,
    PRIMARY KEY (userid)
);
sequelize model:generate --name profile --attributes userid:integer ,picture:string,about:string,religion:string,birth:date,jop:string,country:string
CREATE TABLE public."Profile"
(
    picture string,
    about string,
    userid integer NOT NULL,
    religion string,
    birth string,
    jop string,
    country string
);
sequelize model:generate --name friends --attributes fr_id:integer , status:integer , created_at:date , user1id:integer , user2id:integer
CREATE TABLE public.friends
(
    status integer NOT NULL,
    dt_created date NOT NULL,
    fr_id integer NOT NULL,
    id_user1 integer NOT NULL,
    id_user2 integer NOT NULL,
    PRIMARY KEY (fr_id)
);
sequelize model:generate --name posts --attributes postid:integer , userid:integer , post_type:integer , body:string  , like_count:integer , com_count:integer, created_at:date , update_at:date
CREATE TABLE public.posts
(
    post_id integer NOT NULL,
    post_type integer NOT NULL,
    "Body" string,
    userid integer NOT NULL,
    created_at date NOT NULL,
    updated_at date,
    like_count integer,
    com_counts integer,
    PRIMARY KEY (post_id)
);
sequelize model:generate --name comment --attributes comment_id:integer , postid:integer , userid:integer , post_type:integer , body:string  , like_count:integer , created_at:date , update_at:date
CREATE TABLE public.comment
(
    comment_id integer NOT NULL,
    post_id integer NOT NULL,
    "Body" string,
    userid integer NOT NULL,
    created_at date NOT NULL,
    updated_at date,
    like_count integer,
    PRIMARY KEY (comment_id)
);
sequelize model:generate --name likes --attributes like_id:integer , postid:integer , reaction_type:integer , created_at:date 

CREATE TABLE public."like"
(
    like_id integer NOT NULL,
    postc_id integer NOT NULL,
    userid integer NOT NULL,
    created_at date NOT NULL,
    "Type" integer NOT NULL,
    PRIMARY KEY (like_id)
);
sequelize model:generate --name notification --attributes notification:integer , userid:integer , notification_type:integer , body:string  , seen:integer ,  created_at:date , update_at:date
CREATE TABLE public."Notifications"
(
    userid integer NOT NULL,
    created_at date NOT NULL,
    "Body" string NOT NULL,
    status integer NOT NULL,
    notification_id integer NOT NULL,
    PRIMARY KEY (notification_id)
);
END;